### PR TITLE
Fix: Show images stored alongside *.md sections

### PR DESCRIPTION
**Pull request by goingforbrooke**

### CODE REVIEW

**Comment by ipetkov** [comment]
Not fully sure how zola's internals interact with this, but as of 733f1c17b939238341a50ce353263e9cc4162fe0 I'll see image urls built like: `https://example.comblog/2022-05-21-title-of-the-post/image.jpg` (yes the domain is malformed due to a missing slash), when in reality the image is available at `https://example.com/blog/title-of-the-post/image.jpg`

**Comment by goingforbrooke** [comment]
The trailing slash issue seems to be long running, though it's [behaving as expected](https://github.com/getzola/zola/pull/1534#issuecomment-1325606503). There's a chance that [shortcodes are broken](https://github.com/getzola/zola/issues/2178) or that [I'm missing something important](https://github.com/getzola/zola/issues/2178) about how they work.

**Comment by goingforbrooke** [comment]
The trailing slash issue seems to be long running, though it's [behaving as expected](https://github.com/getzola/zola/pull/1534#issuecomment-1325606503). There's also a chance that [shortcodes are broken](https://github.com/getzola/zola/issues/2178) or that [I'm missing something important](https://github.com/getzola/zola/issues/2178) about how they work.

**Comment by goingforbrooke** [comment]
I'm testing a version of my site with `zola serve` and I'm not getting @ipetkov's [slash issue](https://github.com/pawroman/zola-theme-terminimal/pull/43#issuecomment-1579818791). My post is defined in `content/post_title/index.md`, which uses `content/post_title/test_image.jpeg` via shortcode the same way that @ipetkov [does in his posts](https://github.com/ipetkov/ipetkov.github.io/blob/43c3471e0bafc3c1a14b2dad0379470e2b37d986/content/blog/2022-05-21-steam-deck-first-impressions/index.md?plain=1#L52).

@ipetkov, are you using `zola serve` when you get the trailing slash issue?

**Comment by ipetkov** [comment]
Yeah I see the issue with both `zola serve` and `zola build`. I'm on `zola 0.17.2` fwiw

**Comment by goingforbrooke** [comment]
Strange-- I'm on `0.17.2` as well. Would you mind pushing a branch of your site with the issue? Post a link to the code here and I'll see if I can reproduce it locally.

**Comment by ipetkov** [comment]
@goingforbrooke sure!

[Here's the source](https://github.com/ipetkov/ipetkov.github.io/tree/broken-links) which builds [this broken version of the site](https://github.com/ipetkov/ipetkov.github.io/tree/gh-pages-broken)

[Here is an example of the broken URLs](https://github.com/ipetkov/ipetkov.github.io/blob/d770eb2b60f2b59af104c15d30baedc5b63ff077/blog/steam-deck-first-impressions/index.html#L131) and this is the corresponding [shortcode which generates it](https://github.com/ipetkov/ipetkov.github.io/blob/203ead9c551513b457e7df059f1898c67ad0ef80/content/blog/2022-05-21-steam-deck-first-impressions/index.md#L51-L54)

[Here is what the non-broken version](https://github.com/ipetkov/ipetkov.github.io/blob/ae590d5ffa86ac5e598e6240d141e53fc429656c/blog/steam-deck-first-impressions/index.html#L121) looks like

**Comment by goingforbrooke** [comment]
Thanks! I haven't run it locally yet, but at first blush, you might be missing a trailing slash in your [`config.toml`'s `base_url`](https://github.com/ipetkov/ipetkov.github.io/blob/43c3471e0bafc3c1a14b2dad0379470e2b37d986/config.toml#L1).

I'm going off [my blog's `base_url`](https://github.com/goingforbrooke/personal_blog/blob/62274e13eea49038f2631bce8461a075e369a5d1/config.toml#L2), which has a trailing slash. On the other hand, [my (Zola) site's `base_url`](https://github.com/goingforbrooke/goingforbrooke.github.io/blob/cbd15ab7e0a2e79376844892c98d55b88fde0cfb/config.toml#L2) doesn't have a trailing slash (and perhaps it should).

I'll try adding a slash to the end of my site's `base_url` and see what happens.

**Comment by ipetkov** [comment]
Doesn't seem to help :/

It adds a redundant (through harmless) slash in some places. The broken image urls are slightly less broken, though now they end up pointing to the root of the domain but not nested under the blog content :thinking:

**Comment by goingforbrooke** [comment]
Zole might not like the dates that you're prefixing to your blog post directories.

For example, your blog post `ipetkov.github.io.content/blog/2022-05-21-steam-deck-first-impressions` is generated as `public/blog/steam-deck-first-impressions` (with the date stripped). For this reasons, the page fails to retrieve `blog/2022-05-21-steam-deck-first-impressions/deck.jpg` because the path doesn't exist. 

I would suggest that you remove the date prefixes from your blog posts, but `figure` shortcodes are working fine with no path to the image at all. For example, [`case_switch.jpg`](https://github.com/ipetkov/ipetkov.github.io/blob/d770eb2b60f2b59af104c15d30baedc5b63ff077/blog/steam-deck-first-impressions/index.html#LL157C1-L157C1). tells me that I'm still missing something about asset colocation. On the other hand, this fix works on my test site, which uses a mix of directory-style and markdown-style posts.

**Comment by ipetkov** [comment]
Zola automatically handles stripping dates from pages (or it's documented as a "feature" at least) because all the other links still work

I did a quick test with the various properties that zola's pages are available in the templates:

```
  path: /blog/steam-deck-first-impressions/
  permalink: http://127.0.0.1:1111/blog/steam-deck-first-impressions/
  relative_path: blog/2022-05-21-steam-deck-first-impressions/index.md
  colocated_path: blog/2022-05-21-steam-deck-first-impressions/
```

Seems like `page.path` gives the actual URL the page will fully be generated at while `colocated_path` represents the relative URL of the markdown page before processing. Actually `page.permalink` seems to pretty much already have the base URL we want, and appending the image name (assuming the argument doesn't include `../`) makes the images resolve for me!

**Comment by goingforbrooke** [comment]
Thanks for going the extra mile to post output and for trying out different properties!

Sadly, using `page.permalink` breaks my site. Where do you see the docs for date stripping in Zola?

## ipetkov.github.io (dates in post titles, subdir style)

✅`config.base_url`+`page.path`: `http://127.0.0.1:1025/blog/steam-deck-first-impressions/deck.jpg`
- Date stripped

✅`page.permalink`: `http://127.0.0.1:1025/blog/steam-deck-first-impressions/deck.jpg`
- Date stripped

❌`config.base_url`+`page.relative_path`: `http://127.0.0.1:1025blog/2022-05-21-steam-deck-first-impressions/index.md`
- Date not stripped
- Adding a `/` to `base_url` in `Cargo.toml` doesn't help.

❌`config.base_url`+`page.colocated_path`: `http://127.0.0.1:1025blog/2022-05-21-steam-deck-first-impressions/deck.jpg`
- Date not stripped
- Adding a `/` to `base_url` in `Cargo.toml` doesn't help.

## My Blog (no dates in post titles, top-level style)

❌`config.base_url`+`page.path`: `http://127.0.0.1:1111//pages-ssg/jekyll_quickstart.png`

❌`page.permalink`: `http://127.0.0.1:1111/pages-ssg/jekyll_quickstart.png`

❌`config.base_url`+`page.relative_path`: `http://127.0.0.1:1111/pages_ssg.md/jekyll_quickstart.png`
- `/` inserted after `relative_path`

✅`config.base_url`+`page.colocated_path`: `http://127.0.0.1:1111/jekyll_quickstart.png`
- `page.colocated_path` is [`null` because the `.md` file isn't colocated](https://www.getzola.org/documentation/templates/pages-sections/)

## Summary

I'd like to use `page.colocated_path`, but it doesn't include the date stripping that your blog needs.

**Comment by goingforbrooke** [comment]
## Solution

Let's use the [`resize_image`](https://www.getzola.org/documentation/content/image-processing/#fit) built-in function for all `image`s (and `figure`s) because it's a reliable way to get a valid "output URL". It works with the directory-post-style that @ipetkov uses and the `*.md`-post-style that I use.

We can preserve the look of existing sites by setting the resize dimensions for [fit](https://www.getzola.org/documentation/content/image-processing/#fit) large enough (5000x5000), that no resizing actually happens.

## Research

@ipetkov, never mind about the docs reference on date stripping-- I found it.

I looked into the docs a bit more and my interpretation is that `page.path` and `page.permalink` are "output paths" on the generated site. The "input paths" `page.relative_path` and `page.colocated_path` are "input paths" before the site is generated. "Input paths" need further processing to be valid. For example, `page.relative_path` doesn't [strip dates](https://www.getzola.org/documentation/content/page/#path-from-filename) from slugs.

As for @ipetkov's `page.permalink` suggestion, it doesn't work for my (`*.md`-post-style) site because it assumes the directory-post-style.

We want to use `page.colocated_paths` to reference images on the input side because (1) [Zola recommends it for shortcodes](https://www.getzola.org/documentation/content/shortcodes/#page-or-section) and (2) it works on `*.md`-post-style sites by [defaulting to `null` when `*.md` isn't colocated](https://www.getzola.org/documentation/templates/pages-sections/#page-variables).

The trouble is getting `page.colocated_path` into the HTML's `src`. In this PR, I convert it to a string and append it to `config.base_url`, but that breaks images in @ipetkov's directory-post-style. The [`get_url` builtin](https://www.getzola.org/documentation/templates/overview/#get-url) offers "Get the permalink for the given path," but it also doesn't strip dates.

**Comment by goingforbrooke** [comment]
Incorporated changes into (new) PR #46.

**Pull request closed without merging**
